@port=3434
@prefix=api/v1
@baseUrl=http://localhost:{{port}}/{{prefix}}


### Get all users
GET {{baseUrl}}/

###te a user

POST {{baseUrl}}/users
content-type: application/json

{
    "username": "te2232323",
    "email": "test12@example.com",
    "password": "test1212",    
    "tmdbApiKey": "test-key"
}

