export const ROUTE_SEGMENT = {
  HOME: '',

  AUTH: 'auth',
  REGISTER: 'register',
  SIGNIN: 'signin',
  CREDENTIALS: 'credentials',
  PLAN: 'plan',
  ACCOUNT: 'account',

  BROWSE: 'browse',
} as const;

export const ROUTE_PATH = {
  HOME: `/${ROUTE_SEGMENT.HOME}`,

  AUTH: `/${ROUTE_SEGMENT.AUTH}`,
  AUTH_REGISTER: `/${ROUTE_SEGMENT.AUTH}/${ROUTE_SEGMENT.REGISTER}`,
  AUTH_SIGNIN: `/${ROUTE_SEGMENT.AUTH}/${ROUTE_SEGMENT.SIGNIN}`,
  AUTH_REGISTER_CREDENTIALS: `/${ROUTE_SEGMENT.AUTH}/${ROUTE_SEGMENT.REGISTER}/${ROUTE_SEGMENT.CREDENTIALS}`,
  AUTH_REGISTER_PLAN: `/${ROUTE_SEGMENT.AUTH}/${ROUTE_SEGMENT.REGISTER}/${ROUTE_SEGMENT.PLAN}`,
  AUTH_REGISTER_ACCOUNT: `/${ROUTE_SEGMENT.AUTH}/${ROUTE_SEGMENT.REGISTER}/${ROUTE_SEGMENT.ACCOUNT}`,

  BROWSE: `/${ROUTE_SEGMENT.BROWSE}`,
} as const;

export const LIGHT_MODE_ROUTES = [ROUTE_PATH.AUTH_REGISTER];
