export const ROUTE_SEGMENTS = {
  DYNAMIC_ID: ':id',
  HOME: '',

  AUTH: 'auth',
  LOGIN: 'login',
  REGISTER: 'register',
  CREDENTIALS: 'credentials',
  PLAN: 'plan',
  ACCOUNT: 'account',

  PROFILE: 'profile',

  BROWSE: 'browse',
} as const;

export const ROUTE_PATHS = {
  HOME: `/${ROUTE_SEGMENTS.HOME}`,

  ACCOUNT: `/${ROUTE_SEGMENTS.ACCOUNT}`,
  ACCOUNT_PROFILE: `/${ROUTE_SEGMENTS.ACCOUNT}/${ROUTE_SEGMENTS.PROFILE}`,

  AUTH: `/${ROUTE_SEGMENTS.AUTH}`,
  AUTH_LOGIN: `/${ROUTE_SEGMENTS.AUTH}/${ROUTE_SEGMENTS.LOGIN}`,
  AUTH_REGISTER: `/${ROUTE_SEGMENTS.AUTH}/${ROUTE_SEGMENTS.REGISTER}`,
  AUTH_REGISTER_CREDENTIALS: `/${ROUTE_SEGMENTS.AUTH}/${ROUTE_SEGMENTS.REGISTER}/${ROUTE_SEGMENTS.CREDENTIALS}`,
  AUTH_REGISTER_PLAN: `/${ROUTE_SEGMENTS.AUTH}/${ROUTE_SEGMENTS.REGISTER}/${ROUTE_SEGMENTS.PLAN}`,
  AUTH_REGISTER_ACCOUNT: `/${ROUTE_SEGMENTS.AUTH}/${ROUTE_SEGMENTS.REGISTER}/${ROUTE_SEGMENTS.ACCOUNT}`,

  BROWSE: `/${ROUTE_SEGMENTS.BROWSE}`,
  BROWSE_DETAIL: `/${ROUTE_SEGMENTS.BROWSE}/${ROUTE_SEGMENTS.DYNAMIC_ID}`,
} as const;

export const LIGHT_MODE_ROUTES = [ROUTE_PATHS.AUTH_REGISTER];

export const API_PATH_SEGMENTS = {
  DYNAMIC_PARAM: {
    ID: ':id',
    EMAIL: ':email',
    TMDB_API_KEY: ':tmdbApiKey',
  },
  AUTH: {
    ROOT: 'auth',
    LOGIN: 'login',
    REGISTER: 'register',
    CHECK_EMAIL: 'check-email',
    CHECK_TMDB_API_KEY: 'check-tmdb-api-key',
    REFRESH: 'refresh-token',
    LOGOUT: 'logout',
  },
  BROWSE: {
    ROOT: 'browse',
  },
  ACCOUNT: {
    ROOT: 'account',
    PROFILE: 'profile',
  },
} as const;

export const API_PATHS = {
  AUTH: `/${API_PATH_SEGMENTS.AUTH.ROOT}`,
  AUTH_LOGIN: `/${API_PATH_SEGMENTS.AUTH.ROOT}/${API_PATH_SEGMENTS.AUTH.LOGIN}`,
  AUTH_REGISTER: `/${API_PATH_SEGMENTS.AUTH.ROOT}/${API_PATH_SEGMENTS.AUTH.REGISTER}`,
  AUTH_CHECK_EMAIL: `/${API_PATH_SEGMENTS.AUTH.ROOT}/${API_PATH_SEGMENTS.AUTH.CHECK_EMAIL}/${API_PATH_SEGMENTS.DYNAMIC_PARAM.EMAIL}`,
  AUTH_CHECK_TMDB_API_KEY: `/${API_PATH_SEGMENTS.AUTH.ROOT}/${API_PATH_SEGMENTS.AUTH.CHECK_TMDB_API_KEY}/${API_PATH_SEGMENTS.DYNAMIC_PARAM.TMDB_API_KEY}`,
  AUTH_REFRESH: `/${API_PATH_SEGMENTS.AUTH.ROOT}/${API_PATH_SEGMENTS.AUTH.REFRESH}`,
  AUTH_LOGOUT: `/${API_PATH_SEGMENTS.AUTH.ROOT}/${API_PATH_SEGMENTS.AUTH.LOGOUT}`,

  ACCOUNT: `/${API_PATH_SEGMENTS.ACCOUNT.ROOT}`,
  ACCOUNT_PROFILE: `/${API_PATH_SEGMENTS.ACCOUNT.ROOT}/${API_PATH_SEGMENTS.ACCOUNT.PROFILE}`,
} as const;
